model: "baseline_qwen_3"

# LLM
llm_path: "Qwen/Qwen3-8B"

# Prompt templates
prompt_templates_file: "prompt_templates/question_prompts.csv"

# LLM parameters
max_new_tokens: 32768

# Quantization: useful for large models and limited computing resources
use_quantization: true

# In-context learning parameters
few_shot: 5

# Data
train_data_file: "data/train.jsonl"